export const data = [
  {
    SoS: 0,
    UAV: 4,
    HELI: 3,
    FRI: 8,
    CUT: 2,
    "Total CS": 17,
    "UAV tactics": "Expanding",
    "HELI tactics": "Creeping",
    "UAV step size": 13,
    "HELI step size": 3,
    "Avergage operating cost [k$]": 1049,
    "Total aqcuicisition cost [M$]": 4391,
    "Failure Rate": 0.48,
    "Average search time [h]": 3.55,
  },
  {
    SoS: 1,
    UAV: 3,
    HELI: 1,
    FRI: 7,
    CUT: 6,
    "Total CS": 17,
    "UAV tactics": "Greedy",
    "HELI tactics": "Greedy",
    "UAV step size": 7,
    "HELI step size": 8,
    "Avergage operating cost [k$]": 986,
    "Total aqcuicisition cost [M$]": 3816,
    "Failure Rate": 0.56,
    "Average search time [h]": 3.9,
  },
  {
    SoS: 2,
    UAV: 2,
    HELI: 4,
    FRI: 0,
    CUT: 6,
    "Total CS": 12,
    "UAV tactics": "Creeping",
    "HELI tactics": "Creeping",
    "UAV step size": 10,
    "HELI step size": 10,
    "Avergage operating cost [k$]": 229,
    "Total aqcuicisition cost [M$]": 62,
    "Failure Rate": 0.36,
    "Average search time [h]": 5.71,
  },
  {
    SoS: 3,
    UAV: 0,
    HELI: 3,
    FRI: 2,
    CUT: 0,
    "Total CS": 5,
    "UAV tactics": "Creeping",
    "HELI tactics": "Greedy",
    "UAV step size": 10,
    "HELI step size": 11,
    "Avergage operating cost [k$]": 490,

    "Total aqcuicisition cost [M$]": 1618.9,
    "Failure Rate": 0.67,
    "Average search time [h]": 5,
  },
  {
    SoS: 4,
    UAV: 1,
    HELI: 1,
    FRI: 5,
    CUT: 9,
    "Total CS": 16,
    "UAV tactics": "Greedy",
    "HELI tactics": "Expanding",
    "UAV step size": 16,
    "HELI step size": 14,
    "Avergage operating cost [k$]": 694,

    "Total aqcuicisition cost [M$]": 2645.8,
    "Failure Rate": 0.48,
    "Average search time [h]": 3.41,
  },
  {
    SoS: 5,
    UAV: 3,
    HELI: 0,
    FRI: 9,
    CUT: 9,
    "Total CS": 21,
    "UAV tactics": "Expanding",
    "HELI tactics": "Expanding",
    "UAV step size": 3,
    "HELI step size": 16,
    "Avergage operating cost [k$]": 1298,
    "Total aqcuicisition cost [M$]": 4882.4,
    "Failure Rate": 0.6,
    "Average search time [h]": 4.05,
  },
  {
    SoS: 6,
    UAV: 4,
    HELI: 2,
    FRI: 5,
    CUT: 4,
    "Total CS": 15,
    "UAV tactics": "Creeping",
    "HELI tactics": "Creeping",
    "UAV step size": 4,
    "HELI step size": 13,
    "Avergage operating cost [k$]": 775,

    "Total aqcuicisition cost [M$]": 2750.3,
    "Failure Rate": 0.22,
    "Average search time [h]": 3.49,
  },
  {
    SoS: 7,
    UAV: 3,
    HELI: 1,
    FRI: 3,
    CUT: 2,
    "Total CS": 9,
    "UAV tactics": "Creeping",
    "HELI tactics": "Greedy",
    "UAV step size": 12,
    "HELI step size": 17,
    "Avergage operating cost [k$]": 490,

    "Total aqcuicisition cost [M$]": 1618.9,
    "Failure Rate": 0.66,
    "Average search time [h]": 5,
  },
  {
    SoS: 8,
    UAV: 1,
    HELI: 2,
    FRI: 9,
    CUT: 4,
    "Total CS": 16,
    "UAV tactics": "Creeping",
    "HELI tactics": "Creeping",
    "UAV step size": 8,
    "HELI step size": 5,
    "Avergage operating cost [k$]": 1093,

    "Total aqcuicisition cost [M$]": 4904.5,
    "Failure Rate": 0.6,
    "Average search time [h]": 4.08,
  },
  {
    SoS: 9,
    UAV: 2,
    HELI: 3,
    FRI: 2,
    CUT: 7,
    "Total CS": 14,
    "UAV tactics": "Expanding",
    "HELI tactics": "Creeping",
    "UAV step size": 11,
    "HELI step size": 7,
    "Avergage operating cost [k$]": 418,
    "Total aqcuicisition cost [M$]": 1133,
    "Failure Rate": 0.32,
    "Average search time [h]": 3.07,
  },
];

export const costs = {
  CUT: {
    init_cost_MUSD: 31,
    "operating_cost_kUSD/h": 3.605 * 60 * 60,
  },
  HEL: {
    init_cost_MUSD: 17.9,
    "operating_cost_kUSD/h": 3.129 * 60 * 60,
  },
  FRI: {
    init_cost_MUSD: 540,
    "operating_cost_kUSD/h": 6.994 * 60 * 60,
  },
  UAV: {
    init_cost_MUSD: 5.304,
    "operating_cost_kUSD/h": 1.916 * 60 * 60,
  },
};
